### PR TITLE
Add support for configuration profiles

### PR DESCRIPTION
**Pull request by dlax**
This stems from the idea discussed at https://github.com/dalibo/pg_activity/pull/387#issuecomment-1623178466.#396.

```
$ cat ~/.config/pg_activity/my.conf 
[database]
hidden = true
```
```
$ pg_activity --profile my  # will use the file above as configuration
```

One thing I wonder is whether the option should be named `--config <full-path-to-config>` or if we should introduce another option later on.

* * *

Based on #404

### CODE REVIEW

**Comment by blogh** [comment]
From what I understand the configuration we can set in the file relate to the columns of the query display. 
@kmoppel-cognite was looking for a way to hide sections of the header (instance, system, workers).

```
  --no-inst-info        Display instance information in header.
  --no-sys-info         Display system information in header.
  --no-proc-info        Display workers process information in header.
```

But I guess other options would be nice to have to.

Did I miss something ?

**Comment by dlax** [comment]
>  From what I understand the configuration we can set in the file relate to the columns of the query display.
> @kmoppel-cognite was looking for a way to hide sections of the header (instance, system, workers).

These are not configurable through configuration files at the moment, 
indeed; but we can certainly add support for these later on.

**Comment by kmoppel** [comment]
Hey, glad to see some progress! Looks promising :)  At the same time - do I understand correctly that currently there is still no "infra" for built-in profiles where configs could be read in some fallback mode from some "flags dictionary" in code?

**Comment by dlax** [comment]
> do I understand correctly that currently there is still no "infra" for built-in profiles where configs could be read in some fallback mode from some "flags dictionary" in code?

Sorry, I don't get your question; can you reformulate?

**Review by blogh — APPROVED** [review]
LGTM, thanks for adding this !

**Pull request merged**
