### PR TITLE
Handle disconnection from postgres and try to reconnect

### PR DESCRIPTION
**Pull request by dlax**
We restore the previous behavior (sort of) that got dropped during ui rewrite by trying 3 times to reconnect in case of disconnection, waiting 5s between each attempts.

### CODE REVIEW

**Comment by dlax** [comment]
cc @blogh, if you want to try this out.

**Comment by blogh** [comment]
cool, I completely missed it while testing.

**Comment by blogh** [comment]
works great.

**Comment by blogh** [comment]
thanks

**Pull request merged**
