### PR TITLE
Enable back setuptools automatic discovery

### LINKED ISSUE #411: setuptools warning
By packaging 3.5.0 on Gentoo Linux I see the following setuptools warning:

```
 * QA Notice: setuptools warnings detected:
 * 
 *      Package 'pgactivity.profiles' is absent from the `packages` configuration.
 *      Package 'pgactivity.queries' is absent from the `packages` configuration.
```

### PR DESCRIPTION
**Pull request by dlax**
Fix #411 

@asarubbo, can you check if this resolves #411 on Gentoo?
@mikelolasagasti, can you check if this change works for Fedora, as this reverts the one from #378?

### CODE REVIEW

**Comment by mikelolasagasti** [comment]
Patched pyproject.toml on top of 3.5.0 and fails with:

~~~
error: Installed (but unpackaged) file(s) found:
   /usr/lib/python3.12/site-packages/docs/imgs/logo-horizontal.png
   /usr/lib/python3.12/site-packages/docs/imgs/logo-horizontal.svg
   /usr/lib/python3.12/site-packages/docs/imgs/logo.svg
   /usr/lib/python3.12/site-packages/docs/imgs/screenshot.png
   /usr/lib/python3.12/site-packages/docs/man/build-man.sh
   /usr/lib/python3.12/site-packages/docs/man/pg_activity.1
   /usr/lib/python3.12/site-packages/docs/man/pg_activity.pod
   /usr/lib/python3.12/site-packages/tests/__pycache__/conftest.cpython-312.opt-1.pyc
   /usr/lib/python3.12/site-packages/tests/__pycache__/conftest.cpython-312.pyc
   /usr/lib/python3.12/site-packages/tests/__pycache__/test_activities.cpython-312.opt-1.pyc
   /usr/lib/python3.12/site-packages/tests/__pycache__/test_activities.cpython-312.pyc
   /usr/lib/python3.12/site-packages/tests/__pycache__/test_config.cpython-312.opt-1.pyc
   /usr/lib/python3.12/site-packages/tests/__pycache__/test_config.cpython-312.pyc
   /usr/lib/python3.12/site-packages/tests/__pycache__/test_data.cpython-312.opt-1.pyc
   /usr/lib/python3.12/site-packages/tests/__pycache__/test_data.cpython-312.pyc
   /usr/lib/python3.12/site-packages/tests/__pycache__/test_types.cpython-312.opt-1.pyc
   /usr/lib/python3.12/site-packages/tests/__pycache__/test_types.cpython-312.pyc
   /usr/lib/python3.12/site-packages/tests/__pycache__/test_views.cpython-312.opt-1.pyc
   /usr/lib/python3.12/site-packages/tests/__pycache__/test_views.cpython-312.pyc
   /usr/lib/python3.12/site-packages/tests/conftest.py
   /usr/lib/python3.12/site-packages/tests/data/local-processes-input.json
   /usr/lib/python3.12/site-packages/tests/test_activities.py
   /usr/lib/python3.12/site-packages/tests/test_config.py
   /usr/lib/python3.12/site-packages/tests/test_data.py
   /usr/lib/python3.12/site-packages/tests/test_scroll.txt
   /usr/lib/python3.12/site-packages/tests/test_types.py
   /usr/lib/python3.12/site-packages/tests/test_ui.txt
   /usr/lib/python3.12/site-packages/tests/test_views.py
   /usr/lib/python3.12/site-packages/tests/test_views.txt
   /usr/lib/python3.12/site-packages/tests/test_widgets.txt
~~~

Environment info:

~~~
INFO: Buildroot is handled by package management downloaded with a bootstrap image:
  rpm-4.19.1-2.fc40.x86_64
  rpm-sequoia-1.5.0-2.fc40.x86_64
  python3-dnf-4.18.2-1.fc40.noarch
  yum-4.18.2-1.fc40.noarch
  dnf5-5.1.10-3.fc40.x86_64
  dnf5-plugins-5.1.10-3.fc40.x86_64
Finish: chroot init
~~~

**Comment by asarubbo** [comment]
> @asarubbo, can you check if this resolves #411 on Gentoo?

It works for me, but it introduces another problem and the package manager denies to install the package:

```
 * python3_10: running distutils-r1_run_phase distutils-r1_python_install
 * The following unexpected files/directories were found top-level
 * in the site-packages directory:
 * 
 *   /usr/lib/python3.10/site-packages/tests
 * 
 * This is most likely a bug in the build system.  More information
 * can be found in the Python Guide:
 * https://projects.gentoo.org/python/guide/qawarn.html#stray-top-level-files-in-site-packages
 * ERROR: dev-db/pg_activity-3.5.0::x-portage failed (install phase):
 *   Failing install because of stray top-level files in site-packages
```

I think it is self-explain, but if you have doubts please let me know.

**Comment by dlax** [comment]
Thank you both for testing.
I just pushed another commit here; can you please try again and report back?

**Comment by asarubbo** [comment]
> Thank you both for testing. I just pushed another commit here; can you please try again and report back?

this works for me. No further errors

**Comment by mikelolasagasti** [comment]
works for me also.

**Pull request merged**
