### PR TITLE
Revamp activity queries, adds options to disable some features and adds logging

### LINKED ISSUE #278: Some of the new header information are not accessible in --rds mode.
Example:

```
psycopg2.errors.InsufficientPrivilege: permission denied for function pg_ls_tmpdir
```

### LINKED ISSUE #300: MacOS: can't get CPU/mem stats
Hi. This looks like a really cool tool but I can not manage to get the CPU% column to show under MacOS (10.15.7).

I launch like this `pg_activity --dbname=web`

I assume I do not need to change the user as homebrew launches processes using my user: 

```
❯ ps aux | grep postgres
viktor             573   0.0  0.0  4488148    400   ??  Ss   30Jun22   0:00.53 postgres: logical replication launcher
viktor             572   0.0  0.0  4341228    700   ??  Ss   30Jun22   1:09.45 postgres: stats collector
viktor             571   0.0  0.0  4488148    956   ??  Ss   30Jun22   0:12.22 postgres: autovacuum launcher
viktor             570   0.0  0.0  4487956     84   ??  Ss   30Jun22   0:20.46 postgres: walwriter
viktor             569   0.0  0.0  4487956    184   ??  Ss   30Jun22   0:05.68 postgres: background writer
viktor             568   0.0  0.0  4488488    220   ??  Ss   30Jun22   0:21.74 postgres: checkpointer
viktor             468   0.0  0.0  4488240    440   ??  S    30Jun22   0:46.32 /usr/local/opt/postgresql/bin/postgres -D /usr/local/var/postgres
viktor           13104   0.0  0.0  4268180    480 s004  R+   12:39pm   0:00.00 grep --color=auto --exclude-dir=.bzr --exclude-dir=CVS --exclude-dir=.git --exclude-dir=.hg --exclude-dir=.svn postgres
viktor           12430   0.0  0.0  4488508   2272   ??  Ss   12:26pm   0:00.01 postgres: viktor web [local] idle
```

On another issue there was a comment to try this, which works: 

```❯ python3 <<EOF
import psutil
print(psutil.virtual_memory())
p = psutil.Process(468)
print(p.cpu_times())
exit()
EOF
svmem(total=8589934592, available=1713590272, percent=80.1, used=5525413888, free=16392192, active=1698951168, inactive=1661759488, wired=3826462720)
pcputimes(user=8.53199872, system=37.791858688, children_user=0.0, children_system=0.0)
```

Screenshot 2022-07-20 at 12 40 29

Apologies if I'm missing something obvious and appreciate any help!

### LINKED ISSUE #301: Traceback: Function pg_stat_get_wal_receiver() is currently not supported in Aurora
Using `pg_activity 3.0.0a1` (commit 560070616458b606efd0c1d06166be0bec534ce9) against an AWS RDS/Aurora database, the following traceback occurs with `psycopg2-binary==2.9.3`

```
$ pg_activity -U <username> -h <host> -d <db> --rds --no-db-size

Traceback (most recent call last):
  File "/home/ubuntu/run2/bin/pg_activity", line 11, in <module>
    load_entry_point('pg-activity==3.0.0a1', 'console_scripts', 'pg_activity')()
  File "/home/ubuntu/run2/lib/python3.8/site-packages/pg_activity-3.0.0a1-py3.8.egg/pgactivity/cli.py", line 347, in main
    ui.main(term, dataobj, host, args)
  File "/home/ubuntu/run2/lib/python3.8/site-packages/pg_activity-3.0.0a1-py3.8.egg/pgactivity/ui.py", line 29, in main
    server_information = data.pg_get_server_information(
  File "/home/ubuntu/run2/lib/python3.8/site-packages/pg_activity-3.0.0a1-py3.8.egg/pgactivity/data.py", line 225, in pg_get_server_information
    cur.execute(
  File "/home/ubuntu/run2/lib/python3.8/site-packages/psycopg2/extras.py", line 146, in execute
    return super().execute(query, vars)
psycopg2.errors.FeatureNotSupported: Function pg_stat_get_wal_receiver() is currently not supported in Aurora
```

### LINKED ISSUE #303: psycopg2.errors.InsufficientPrivilege error when using an installation from github
Steps to reproduce:

1.  Follow the "Installation from the git repository" steps in the README:

```
$ git clone https://github.com/dalibo/pg_activity.git
$ cd pg_activity
$ python3 -m venv .venv
$ . .venv/bin/activate
(.venv) $ pip install psycopg2-binary .
(.venv) $ pg_activity
```

3. Run `sudo $(which pg_activity) --rds [connection_string]`
where connection_string is of the format `postgresql://[user[:password]@][netloc][:port][/dbname]`

Expected result: connects to the postgres RDS database
Actual result:

```
Traceback (most recent call last):
  File "/home/ubuntu/pg_activity/.venv/bin/pg_activity", line 8, in <module>
    sys.exit(main())
  File "/home/ubuntu/pg_activity/.venv/lib/python3.7/site-packages/pgactivity/cli.py", line 347, in main
    ui.main(term, dataobj, host, args)
  File "/home/ubuntu/pg_activity/.venv/lib/python3.7/site-packages/pgactivity/ui.py", line 32, in main
    skip_sizes=options.nodbsize,
  File "/home/ubuntu/pg_activity/.venv/lib/python3.7/site-packages/pgactivity/data.py", line 231, in pg_get_server_information
    "using_rds": using_rds,
  File "/home/ubuntu/pg_activity/.venv/lib/python3.7/site-packages/psycopg2/extras.py", line 146, in execute
    return super().execute(query, vars)
psycopg2.errors.InsufficientPrivilege: permission denied for function pg_ls_dir
```

Note: this issue does not happen when using the pg_activity installed from the postgresql APT repo: `sudo pg_activity --rds postgresql://[user[:password]@][netloc][:port][/dbname]`

The reason I need to install from git is because I am facing [this bug](https://github.com/dalibo/pg_activity/issues/275) (I am able to connect to the db, but the connection drops after about 10 seconds due to the exception `psycopg2.errors.InvalidTextRepresentation: invalid input syntax for type bytea`)

It looks like that bug was fixed in May, so I'm assuming the fix didn't get included in the April release of 2.3.1

### PR DESCRIPTION
**Pull request by blogh**
closes #303, closes #301, closes #300, closes #278

### CODE REVIEW

**Comment by dlax** [comment]
Can you open a dedicated PR for each commit? That'd be easier to review or iterate on, and we can them merge them separately (and hopefully faster).

**Comment by blogh** [comment]
humm. Will try to separate the logging and the rest so that they can be comited separately.
As is, the logging adds logging to parts that are introduced in the revamp.

**Comment by blogh** [comment]
Just pushed #305  and #306.
I'll add the logging for the codded added here where the #305 is merged.

**Comment by blogh** [comment]
Added #307 for the hints

**Pull request closed without merging**
