### PR TITLE
Fix parallel workers under the lead process in UI via ORDER BY

### PR DESCRIPTION
**Pull request by kmoppel-cognite**
Currently they're jumping around annoyingly. Relevant for vers >= 9.6

### CODE REVIEW

**Comment by kmoppel-cognite** [comment]
Currently something like this happens:  Screenshot from 2022-05-03 14-02-26

**Comment by kmoppel-cognite** [comment]
Or such: 
Screenshot from 2022-05-03 14-35-03

**Comment by kmoppel-cognite** [comment]
After patch: 
Screenshot from 2022-05-03 14-34-25

**Comment by dlax** [comment]
> Indeed, it might be worth trying:

Pushed this suggestion into `procs-sort` branch, if you can give it a try; @blogh, @kmoppel-cognite.

**Comment by kmoppel-cognite** [comment]
@dlax  Oh I see, sorted in code instead. But the above comment didn't work for me sadly - this did:


```diff
diff --git a/pgactivity/activities.py b/pgactivity/activities.py
index bcb989c..31636eb 100644
--- a/pgactivity/activities.py
+++ b/pgactivity/activities.py
@@ -198,7 +198,7 @@ def sorted(processes: List[T], *, key: SortKey, reverse: bool = False) -> List[T
     """
     return builtins.sorted(
         processes,
-        key=lambda p: (getattr(p, key.name) or 0, p.pid),  # TODO: avoid getattr()
+        key=lambda p: (getattr(p, key.name) or (p.duration, p.pid)),  # TODO: avoid getattr()
         reverse=reverse,
     )

```

**Comment by kmoppel-cognite** [comment]
Closing in favour of Python code based sorting  #291

**Pull request closed without merging**
