### PR TITLE
Add a new output column "rollback ratio"

### PR DESCRIPTION
**Pull request by kmoppel-cognite**
To the global / instance info section. To quickly understand if something wrong with queries

Screenshot from 2023-07-01 11-36-17

### CODE REVIEW

**Comment by kmoppel-cognite** [comment]
This makes that view row a bit more longer than others - not a real problem for most screens I guess, but would a bit nicer if things are more aligned. Ideas to "compact" the existing columns:
1) Shorten the "uptime" when its in > 1day - no real need for "minutes" then
2) Remove "and" from "uptime" - unnecessary, the shorter the better
3) "cache hit ratio" -> "cache ratio"

Does that sound like an OK idea ? Could send another PR for that

**Review by dlax — APPROVED** [review]
This looks good to me; thank you @kmoppel-cognite!

@blogh, what do you think?

* * *
TODO before merging:
- [x] squash commits
- [x] add an entry in the changelog

**Comment by blogh** [comment]
Thanks for the addition.

As fat as compacting the columns go : it's a good idea too.

I would go for "cache hit %" instead of "cache ratio". 
Same for "rollback %".

**Review by blogh — APPROVED** [review]

**Comment by dlax** [comment]
> TODO before merging:

I'll take care of this now, and then merge.

**Comment by dlax** [comment]
Merged; thank you @kmoppel-cognite.

**Comment by dlax** [comment]
@kmoppel-cognite:
> Ideas to "compact" the existing columns:
> [...]
> Does that sound like an OK idea ? Could send another PR for that

Sounds good; please go ahead.

**Pull request merged**
